spring.application.name=citizen-management-system-back-end

# 1. C?u h�nh JWT (Quan tr?ng cho ph?n Auth b?n ?ang l�m)
citizen.app.jwtSecret=HbMq1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
citizen.app.jwtExpirationMs=86400000

# 2. C?u h�nh k?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/citizen_db
spring.datasource.username=postgres
spring.datasource.password=080205
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. C?u h�nh JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
