spring.application.name=citizen-management-system-back-end

<<<<<<< HEAD
# 1. Cau hinh JWT (Quan trong cho phan Auth ban dang lam)
citizen.app.jwtSecret=HbMq1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
citizen.app.jwtExpirationMs=86400000

# 2. Cau hinh PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/citizen_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:07112005}
=======
citizen.app.jwtSecret=HbMq1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
citizen.app.jwtExpirationMs=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/citizen_db
spring.datasource.username=postgres
spring.datasource.password=080205
>>>>>>> origin/revert-41-revert-38-feature/nhankhau-management
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
