spring.application.name=citizen-management-system-back-end

citizen.app.jwtSecret=HbMq1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
citizen.app.jwtExpirationMs=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/citizen_db
spring.datasource.username=postgres
spring.datasource.password=080205
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
